export const ADD_NOTE_START = 'ADD_NOTE_START'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE'

export const ADD_QUICK_NOTE_START = 'ADD_QUICK_NOTE_START'
export const ADD_QUICK_NOTE_SUCCESS = 'ADD_QUICK_NOTE_SUCCESS'
export const ADD_QUICK_NOTE_FAILURE = 'ADD_QUICK_NOTE_FAILURE'

export const GET_NOTES_START = 'GET_NOTES_START'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE'

export const GET_QUICK_NOTES_START = 'GET_QUICK_NOTES_START'
export const GET_QUICK_NOTES_SUCCESS = 'GET_QUICK_NOTES_SUCCESS'
export const GET_QUICK_NOTES_FAILURE = 'GET_QUICK_NOTES_FAILURE'

export const GET_NOTE_BY_ID_START = 'GET_NOTE_BY_ID_START'
export const GET_NOTE_BY_ID_SUCCESS = 'GET_NOTE_BY_ID_SUCCESS'
export const GET_NOTE_BY_ID_FAILURE = 'GET_NOTE_BY_ID_FAILURE'

export const UPDATE_NOTE_START = 'UPDATE_NOTE_START'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE'

export const UPDATE_NECESSITY_START = 'UPDATE_NECESSITY_START'
export const UPDATE_NECESSITY_SUCCESS = 'UPDATE_NECESSITY_SUCCESS'
export const UPDATE_NECESSITY_FAILURE = 'UPDATE_NECESSITY_FAILURE'

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE'

export const DELETE_NOTE_START = 'DELETE_NOTE_START'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE'